# Generated by Django 5.1.4 on 2024-12-28 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_student_address_student_belongs_to_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
